"use client";

import Image from "next/image";
import { Bell, CalendarDays, Check, ChevronDown, Heart, IndianRupee, MapPin, Share2, ShieldCheck, Star } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import { faqs, features, model, quickSpecs, variants } from "@/components/model/modelData";
import ModelVariantRangeSection from "@/components/model-premium/ModelVariantRangeSection";

const nav = [["overview","Overview"],["variants","Variants"],["performance","Performance"],["features","Features"],["safety","Safety"],["gallery","Gallery"],["ownership","Ownership"],["reviews","Reviews"]] as const;
const safety = ["6 airbags as standard","5-star Bharat NCAP rating","Level 2 ADAS on select variants","Electronic stability control","360-degree surround camera","ISOFIX child-seat mounts"];
const dimensions = [{label:"Boot space",value:"445 L"},{label:"Ground clearance",value:"205 mm"},{label:"Wheelbase",value:"2,741 mm"},{label:"Fuel tank",value:"50 L"}];
const rivals = [{name:"Mahindra XUV700",price:"Rs. 14.49 - 25.14 Lakh",score:"4.6"},{name:"MG Hector",price:"Rs. 14.25 - 22.89 Lakh",score:"4.5"},{name:"Jeep Compass",price:"Rs. 18.99 - 32.41 Lakh",score:"4.4"}];
const performance = [{label:"Max power",value:"170 PS",detail:"at 3,750 rpm"},{label:"Peak torque",value:"350 Nm",detail:"1,750-2,500 rpm"},{label:"Claimed mileage",value:"16.8 km/l",detail:"manual transmission"},{label:"Fuel tank",value:"50 L",detail:"diesel"}];
const eyebrow = "text-[10px] font-bold uppercase text-[#667b72] dark:text-white/45";
const heading = "mt-3 text-[28px] font-semibold leading-tight text-[#0d2019] dark:text-white sm:text-[34px]";
const section = "scroll-mt-14 py-14 sm:py-16";

export default function ModelPage() {
  const [variant, setVariant] = useState(variants[1]);
  const [down, setDown] = useState(4.75);
  const [years, setYears] = useState(5);
  const emi = useMemo(() => { const p = Math.max(23.64 - down, 0) * 100000; const r = 9.25 / 1200; const n = years * 12; return Math.round(p * r * (1 + r) ** n / ((1 + r) ** n - 1)); }, [down, years]);

  return <main className="overflow-x-hidden pb-16 lg:pb-0">
    <section className="border-b border-black/10 bg-[#eef3ef] dark:border-white/10 dark:bg-[#071b16]"><div className="page-shell py-7">
      <p className="text-[10px] text-[#718078] dark:text-white/45">Cars / Tata / Harrier</p>
      <div className="mt-5 flex flex-wrap items-end justify-between gap-5"><div><p className={eyebrow}>{model.brand} · Premium SUV</p><h1 className="mt-2 text-[40px] font-semibold leading-none text-[#0b1d17] dark:text-white sm:text-[52px]">{model.name}</h1><p className="mt-3 text-[13px] text-[#62716b] dark:text-white/60">{model.tagline}</p></div><div className="flex items-center gap-2"><span className="flex h-9 items-center gap-1.5 rounded-full border border-black/10 bg-white px-3 text-[10px] font-semibold dark:border-white/10 dark:bg-white/5"><Star size={13} fill="#86a51a" className="text-[#86a51a]" />{model.rating}<span className="font-normal text-[#7d8983]">{model.reviewCount}</span></span><IconButton label="Save model" icon={Heart}/><IconButton label="Share model" icon={Share2}/></div></div>
      <div className="mt-7 grid overflow-hidden rounded-[8px] border border-black/10 bg-white shadow-[0_18px_50px_rgba(8,35,28,.10)] dark:border-white/10 dark:bg-[#0d251f] lg:grid-cols-[1.55fr_.75fr]"><div className="relative min-h-[340px] sm:min-h-[470px]"><Image src="/images/model-premium-exterior.png" alt="Deep green premium SUV exterior" fill priority sizes="(max-width:1024px) 100vw,68vw" className="object-cover" /></div><div className="border-t border-black/10 p-7 dark:border-white/10 lg:border-l lg:border-t-0 lg:p-9"><p className="text-[10px] text-[#78857f] dark:text-white/45">Ex-showroom price</p><p className="mt-1 text-[24px] font-semibold text-[#10271f] dark:text-white">{model.price}</p><label className="mt-7 grid gap-2 text-[10px] font-semibold dark:text-white/70">Choose variant<span className="relative"><select value={variant.name} onChange={e => setVariant(variants.find(v => v.name === e.target.value) ?? variants[0])} className="h-11 w-full appearance-none rounded-[6px] border border-black/10 bg-white px-3 text-[11px] dark:border-white/10 dark:bg-[#102e26]">{variants.map(v => <option key={v.name}>{v.name}</option>)}</select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-3.5" /></span></label><div className="mt-4 flex h-11 items-center gap-2 rounded-[6px] border border-black/10 px-3 text-[11px] font-semibold dark:border-white/10"><MapPin size={14}/>New Delhi</div><button className="mt-6 h-11 w-full rounded-full bg-[#c9ff49] text-[11px] font-bold text-[#10271f]">Get on-road price</button><button className="mt-2 h-11 w-full rounded-full border border-[#496e61] text-[11px] font-semibold dark:border-white/25">Book test drive</button></div></div>
      <div className="grid grid-cols-2 border-x border-b border-black/10 bg-white dark:border-white/10 dark:bg-[#0d251f] sm:grid-cols-5">{quickSpecs.map(s => <div key={s.label} className="border-r border-t border-black/10 px-4 py-4 dark:border-white/10 sm:border-t-0"><p className="text-[9px] text-[#7b8882]">{s.label}</p><p className="mt-1 text-[12px] font-semibold dark:text-white">{s.value}</p></div>)}</div>
    </div></section>
    <nav aria-label="Model sections" className="sticky top-0 z-30 border-b border-black/10 bg-white/95 backdrop-blur dark:border-white/10 dark:bg-[#081b16]/95"><div className="page-shell flex h-12 items-center gap-7 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{nav.map(([id,label]) => <a key={id} href={`#${id}`} className="shrink-0 text-[11px] font-semibold text-[#52665e] hover:text-[#68830e] dark:text-white/60">{label}</a>)}</div></nav>
    <Band id="overview"><div className="page-shell grid gap-10 lg:grid-cols-[1.05fr_.95fr] lg:gap-16"><div><Title overline="Model overview">A confident SUV built for long journeys</Title><p className="mt-5 max-w-[650px] text-[12px] leading-6 text-[#5f6e67] dark:text-white/60">The Harrier combines strong diesel performance with an airy cabin, composed road manners and a broad safety package. It is especially compelling when highway comfort, space and road presence matter most.</p></div><div className="grid gap-7 sm:grid-cols-2"><List title="What stands out" items={["Comfortable long-distance ride","Strong road presence","Useful safety technology"]}/><List title="Worth knowing" items={["Diesel-only powertrain","Premium features sit higher up","Large for tight parking"]}/></div></div></Band>
    <ModelVariantRangeSection />
    <section id="performance" className={`${section} bg-[#08241d] text-white`}><div className="page-shell"><p className="text-[10px] font-bold uppercase text-white/55">Engine and efficiency</p><h2 className="mt-3 text-[28px] font-semibold leading-tight sm:text-[34px]">Strong where everyday driving needs it</h2><div className="mt-9 grid border-l border-t border-white/15 sm:grid-cols-2 lg:grid-cols-4">{performance.map(x => <div key={x.label} className="border-b border-r border-white/15 p-6"><p className="text-[10px] text-white/45">{x.label}</p><p className="mt-2 text-[22px] font-semibold">{x.value}</p><p className="mt-2 text-[10px] text-white/45">{x.detail}</p></div>)}</div><div className="mt-8 grid gap-6 border-t border-white/15 pt-8 md:grid-cols-3">{[["Eco","Measured city driving"],["City","Balanced everyday response"],["Sport","Sharper open-road response"]].map(([a,b]) => <div key={a}><p className="text-[11px] font-semibold text-[#c9ff49]">{a}</p><p className="mt-2 text-[10px] text-white/50">{b}</p></div>)}</div></div></section>
    <Band id="features"><div className="page-shell"><Title overline="Feature highlights">Comfort and confidence, thoughtfully combined</Title><div className="mt-9 grid border-l border-t border-black/10 dark:border-white/10 sm:grid-cols-2 lg:grid-cols-4">{features.map(f => {const Icon=f.icon; return <div key={f.title} className="min-h-40 border-b border-r border-black/10 p-6 dark:border-white/10"><Icon size={18} className="text-[#6f8c12] dark:text-[#c9ff49]"/><h3 className="mt-5 text-[13px] font-semibold dark:text-white">{f.title}</h3><p className="mt-2 text-[10px] leading-5 text-[#6b7872] dark:text-white/50">{f.text}</p></div>})}</div></div></Band>
    <Band id="safety" tint><div className="page-shell grid gap-12 lg:grid-cols-2 lg:gap-16"><div><Title overline="Safety">Protection engineered into every journey</Title><div className="mt-7 grid gap-4 sm:grid-cols-2">{safety.map(x => <p key={x} className="flex gap-3 text-[11px] leading-5 dark:text-white/65"><ShieldCheck size={15} className="shrink-0 text-[#789611]"/>{x}</p>)}</div></div><div><Title overline="Space and practicality">Made for people and luggage</Title><div className="mt-7 grid grid-cols-2 border-l border-t border-black/10 dark:border-white/10">{dimensions.map(x => <div key={x.label} className="min-h-28 border-b border-r border-black/10 p-5 dark:border-white/10"><p className="text-[10px] text-[#718078]">{x.label}</p><p className="mt-2 text-[19px] font-semibold dark:text-white">{x.value}</p></div>)}</div></div></div></Band>
    <Band id="gallery"><div className="page-shell"><Title overline="Exterior and interior">Explore the Harrier in detail</Title><div className="mt-8 grid gap-3 lg:grid-cols-[1.35fr_.85fr]"><Gallery src="/images/model-premium-exterior.webp" alt="Premium SUV exterior" label="Exterior design" large/><Gallery src="/images/model-premium-interior.webp" alt="Premium SUV cabin" label="Cabin comfort"/></div></div></Band>
    <Band id="ownership" tint><div className="page-shell grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div><Title overline="Ownership planning">Plan beyond the showroom price</Title><p className="mt-4 text-[11px] leading-5 text-[#65736c] dark:text-white/55">Estimate finance first, then account for registration, insurance, warranty and service.</p></div><div className="rounded-[8px] border border-black/10 bg-white p-6 dark:border-white/10 dark:bg-[#102720] sm:p-8"><p className="text-[10px] text-[#75827c]">Estimated monthly EMI</p><p className="mt-1 text-[25px] font-semibold dark:text-white">Rs. {new Intl.NumberFormat("en-IN").format(emi)}</p><div className="mt-7 grid gap-6"><Range label="Down payment" value={`Rs. ${down.toFixed(2)} Lakh`} min="2.5" max="12" step=".25" current={down} update={setDown}/><Range label="Loan tenure" value={`${years} years`} min="3" max="7" current={years} update={setYears}/></div><div className="mt-7 grid grid-cols-2 gap-4 border-t border-black/10 pt-5 text-[10px] dark:border-white/10"><span className="text-[#718078]">Selected variant</span><span className="text-right font-semibold dark:text-white">{variant.name} · {variant.price}</span><span className="text-[#718078]">Warranty</span><span className="text-right font-semibold dark:text-white">3 years / 1 lakh km</span></div></div></div></Band>
    <Band id="reviews"><div className="page-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className={eyebrow}>Owner reviews</p><div className="mt-4 flex items-end gap-3"><span className="text-[52px] font-semibold leading-none dark:text-white">4.7</span><div className="pb-1"><div className="flex text-[#86a51a]">{Array.from({length:5}).map((_,i) => <Star key={i} size={14} fill="currentColor"/>)}</div><p className="mt-2 text-[10px] text-[#748078]">1,248 verified reviews</p></div></div></div><div>{[["Design",4.8],["Comfort",4.7],["Performance",4.6],["Safety",4.8],["Value",4.5]].map(([l,s]) => <div key={l} className="mb-4 grid grid-cols-[90px_1fr_30px] items-center gap-4 text-[11px]"><span>{l}</span><div className="h-1.5 rounded-full bg-black/10 dark:bg-white/10"><div className="h-full rounded-full bg-[#789611]" style={{width:`${Number(s)/5*100}%`}}/></div><b>{s}</b></div>)}<blockquote className="mt-7 border-l-2 border-[#94ad3f] pl-5 text-[12px] leading-6 text-[#506159] dark:text-white/60">“Comfortable over long distances, confident on rough roads and genuinely spacious for five.”<footer className="mt-3 text-[10px] font-semibold">Rahul K. · Adventure Plus owner</footer></blockquote></div></div></Band>
    <Band tint><div className="page-shell grid gap-12 lg:grid-cols-2 lg:gap-16"><div><Title overline="Compare alternatives">Other SUVs worth a look</Title><div className="mt-7 border-t border-black/10 dark:border-white/10">{rivals.map(r => <div key={r.name} className="flex items-center justify-between border-b border-black/10 py-5 dark:border-white/10"><div><h3 className="text-[13px] font-semibold dark:text-white">{r.name}</h3><p className="mt-1 text-[10px] text-[#748078]">{r.price}</p></div><span className="flex gap-1 text-[10px] font-semibold"><Star size={12} fill="#86a51a" className="text-[#86a51a]"/>{r.score}</span></div>)}</div></div><div><Title overline="Latest stories">Harrier news and guides</Title>{["Harrier receives new connected-car features","Smart vs Pure Plus: which variant fits?","Comfort, mileage and highway manners tested"].map((x,i) => <article key={x} className="border-b border-black/10 py-5 dark:border-white/10"><p className="text-[9px] font-semibold uppercase text-[#6d8914]">{i===0?"Update":i===1?"Buying guide":"Road test"}</p><h3 className="mt-2 text-[13px] font-semibold dark:text-white">{x}</h3></article>)}</div></div></Band>
    <Band><div className="page-shell grid gap-9 lg:grid-cols-[.65fr_1.35fr]"><Title overline="Common questions">Tata Harrier FAQs</Title><div className="border-t border-black/10 dark:border-white/10">{faqs.map((f,i) => <details key={f.question} open={i===0} className="group border-b border-black/10 dark:border-white/10"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-5 py-4 text-[12px] font-semibold dark:text-white">{f.question}<ChevronDown size={14}/></summary><p className="pb-5 pr-10 text-[10px] leading-5 text-[#69766f] dark:text-white/50">{f.answer}</p></details>)}</div></div></Band>
    <section className="bg-[#08241d] py-12 text-white"><div className="page-shell grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-bold uppercase text-white/55">Ready to take the next step?</p><h2 className="mt-3 max-w-[700px] text-[28px] font-semibold leading-tight">Get a city-specific price and the latest available offers</h2></div><div className="flex flex-col gap-3 sm:flex-row"><button className="inline-flex h-11 items-center justify-center gap-2 rounded-full bg-[#c9ff49] px-6 text-[11px] font-bold text-[#10271f]"><IndianRupee size={15}/>Get exact price</button><button className="inline-flex h-11 items-center justify-center gap-2 rounded-full border border-white/25 px-6 text-[11px] font-semibold"><Bell size={15}/>Set price alert</button></div></div></section>
    <div className="fixed inset-x-0 bottom-0 z-40 overflow-hidden border-t border-black/10 bg-white p-3 shadow-[0_-10px_30px_rgba(0,0,0,.08)] dark:bg-[#0b211b] lg:hidden"><div className="mx-auto grid w-full max-w-md grid-cols-2 gap-2"><button className="inline-flex h-11 min-w-0 items-center justify-center gap-2 rounded-full border border-[#496e61] px-2 text-[10px] font-semibold dark:text-white"><CalendarDays size={14}/>Test drive</button><button className="h-11 min-w-0 rounded-full bg-[#c9ff49] px-2 text-[10px] font-bold text-[#10271f]">Get on-road price</button></div></div>
  </main>;
}

function Band({id,tint=false,children}:{id?:string;tint?:boolean;children:ReactNode}) { return <section id={id} className={`${section} ${tint?"bg-[#f3f6f3] dark:bg-[#071b16]":"bg-white dark:bg-[#0a1d18]"}`}>{children}</section>; }
function Title({overline,children}:{overline:string;children:ReactNode}) { return <div><p className={eyebrow}>{overline}</p><h2 className={heading}>{children}</h2></div>; }
function IconButton({label,icon:Icon}:{label:string;icon:typeof Heart}) { return <button type="button" aria-label={label} title={label} className="grid h-9 w-9 place-items-center rounded-full border border-black/10 bg-white text-[#40584e] dark:border-white/10 dark:bg-white/5 dark:text-white"><Icon size={15}/></button>; }
function List({title,items}:{title:string;items:string[]}) { return <div><h3 className="text-[13px] font-semibold dark:text-white">{title}</h3>{items.map(x => <p key={x} className="mt-4 flex gap-2 text-[11px] text-[#596961] dark:text-white/60"><Check size={14} className="text-[#789611]"/>{x}</p>)}</div>; }
function Gallery({src,alt,label,large=false}:{src:string;alt:string;label:string;large?:boolean}) { return <figure className={`relative overflow-hidden rounded-[8px] ${large?"min-h-[340px] sm:min-h-[500px]":"min-h-[300px]"}`}><Image src={src} alt={alt} fill sizes={large?"(max-width:1024px) 100vw,65vw":"(max-width:1024px) 100vw,35vw"} className="object-cover"/><figcaption className="absolute bottom-4 left-4 rounded-[5px] bg-black/60 px-3 py-2 text-[9px] text-white">{label}</figcaption></figure>; }
function Range({label,value,min,max,step="1",current,update}:{label:string;value:string;min:string;max:string;step?:string;current:number;update:(n:number)=>void}) { return <label className="grid gap-3 text-[10px] font-semibold dark:text-white/70"><span className="flex justify-between"><span>{label}</span><span>{value}</span></span><input type="range" min={min} max={max} step={step} value={current} onChange={e=>update(+e.target.value)} className="accent-[#789611]"/></label>; }
