import { Armchair, Camera, Gauge, MonitorSmartphone, ShieldCheck, SunMedium, type LucideIcon } from "lucide-react";

export const model = { brand: "Tata", name: "Harrier", tagline: "Commanding presence. Confidence for every road.", rating: "4.7", reviews: "1,248 reviews", price: "Rs. 15.00 - 26.50 Lakh", image: "/images/model-premium-exterior.png" };
export const links = [["overview","Overview"],["variants","Variants"],["performance","Performance"],["features","Features"],["safety","Safety"],["gallery","Gallery"],["ownership","Ownership"],["reviews","Reviews"]] as const;
export const specs = [{label:"Engine",value:"1956 cc"},{label:"Power",value:"170 PS"},{label:"Torque",value:"350 Nm"},{label:"Mileage",value:"16.8 km/l"},{label:"Seating",value:"5 seats"}];
export const variants = [{name:"Smart",gear:"Manual",price:"Rs. 15.00 Lakh",note:"Essential safety and connected LED lighting"},{name:"Pure Plus",gear:"Manual / Automatic",price:"Rs. 18.85 Lakh",note:"Panoramic sunroof and premium infotainment"},{name:"Adventure Plus",gear:"Manual / Automatic",price:"Rs. 23.64 Lakh",note:"360-degree camera and terrain response"},{name:"Fearless Plus",gear:"Automatic",price:"Rs. 26.50 Lakh",note:"ADAS, ventilated seats and JBL audio"}];
export type Feature={title:string;text:string;icon:LucideIcon};
export const features:Feature[]=[{title:"Six-airbag safety",text:"Comprehensive protection is standard across the range.",icon:ShieldCheck},{title:"Panoramic sunroof",text:"A wide glass roof brings more light into every row.",icon:SunMedium},{title:"Ventilated comfort",text:"Powered front seats support longer journeys.",icon:Armchair},{title:"Digital cockpit",text:"Twin displays keep media and driving data clear.",icon:MonitorSmartphone},{title:"Surround view",text:"A 360-degree camera simplifies tight spaces.",icon:Camera},{title:"Terrain response",text:"Selectable modes adapt to changing road surfaces.",icon:Gauge}];
export const safety=["6 airbags as standard","5-star Bharat NCAP rating","Level 2 ADAS on select variants","Electronic stability control","360-degree surround camera","ISOFIX child-seat mounts"];
export const dimensions=[{label:"Boot space",value:"445 L"},{label:"Ground clearance",value:"205 mm"},{label:"Wheelbase",value:"2,741 mm"},{label:"Fuel tank",value:"50 L"}];
export const rivals=[{name:"Mahindra XUV700",price:"Rs. 14.49 - 25.14 Lakh",score:"4.6"},{name:"MG Hector",price:"Rs. 14.25 - 22.89 Lakh",score:"4.5"},{name:"Jeep Compass",price:"Rs. 18.99 - 32.41 Lakh",score:"4.4"}];
export const faqs=[{q:"What is the Tata Harrier price range?",a:"The indicative ex-showroom range is Rs. 15.00 lakh to Rs. 26.50 lakh. Final pricing varies by variant, city, registration and insurance."},{q:"Is an automatic transmission available?",a:"Yes. Select variants offer a 6-speed automatic, while a 6-speed manual is available across the range."},{q:"How many people can the Harrier seat?",a:"It is a five-seat SUV with a spacious second row and a listed 445-litre boot."},{q:"Which variants include ADAS?",a:"Driver assistance features are offered on selected higher variants. Confirm the final equipment list before purchase."}];
