"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, CalendarDays, Check, ChevronDown, Gauge, IndianRupee, MapPin, Palette, Settings2, ShieldCheck, Sparkles, Star, Wrench } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";

const car = { brand:"Tata", model:"Harrier", name:"Pure Plus", fuel:"Diesel", transmission:"6-speed Manual", price:18.85, priceLabel:"Rs. 18.85 Lakh", mileage:"16.8 km/l", engine:"1956 cc", power:"170 PS", torque:"350 Nm", image:"/images/model-premium-exterior.webp" };
const highlights = ["Panoramic sunroof","10.25-inch touchscreen","Wireless Android Auto and Apple CarPlay","Automatic climate control","Rear parking camera","Cruise control"];
const groups = [
  {title:"Comfort and convenience",items:["Panoramic sunroof","Automatic climate control","Height-adjustable driver seat","Rear AC vents","Push-button start","Cruise control"]},
  {title:"Infotainment and connectivity",items:["10.25-inch touchscreen","Wireless Android Auto","Wireless Apple CarPlay","Connected car technology","Six-speaker audio","USB-C charging"]},
  {title:"Exterior",items:["LED projector headlamps","LED daytime running lamps","17-inch alloy wheels","Roof rails","Shark-fin antenna","Rear spoiler"]},
];
const safety = ["6 airbags","Electronic stability control","Hill-hold control","Traction control","ISOFIX child-seat mounts","Rear parking camera","Tyre-pressure monitoring","All-wheel disc brakes"];
const specs = [["Engine","2.0L Kryotec turbo diesel"],["Displacement","1956 cc"],["Max power","170 PS @ 3,750 rpm"],["Max torque","350 Nm @ 1,750-2,500 rpm"],["Transmission","6-speed manual"],["Drive type","Front-wheel drive"],["Claimed mileage","16.8 km/l"],["Fuel tank","50 litres"],["Seating capacity","5"],["Boot space","445 litres"],["Ground clearance","205 mm"],["Wheelbase","2,741 mm"]];
const colors = [{name:"Seaweed Green",value:"#536c60"},{name:"Oberon Black",value:"#151a18"},{name:"Lunar White",value:"#e5e8e4"},{name:"Sunlit Yellow",value:"#b89b36"}];
const eyebrow = "text-[10px] font-bold uppercase text-[#667b72] dark:text-white/45";
const heading = "mt-3 text-[28px] font-semibold leading-tight text-[#0d2019] dark:text-white sm:text-[34px]";
const section = "scroll-mt-14 py-14 sm:py-16";

export default function VariantPage() {
  const [city,setCity]=useState("New Delhi");
  const [color,setColor]=useState(colors[0]);
  const [down,setDown]=useState(4);
  const [years,setYears]=useState(5);
  const emi=useMemo(()=>{const p=Math.max(car.price-down,0)*100000,r=9.25/1200,n=years*12;return Math.round(p*r*(1+r)**n/((1+r)**n-1));},[down,years]);

  return <main className="overflow-x-hidden pb-20 lg:pb-0">
    <section className="border-b border-black/10 bg-[#eef3ef] dark:border-white/10 dark:bg-[#071b16]"><div className="page-shell py-7 sm:py-9">
      <Link href="/model" className="inline-flex items-center gap-2 text-[10px] font-semibold text-[#53685f] hover:text-[#6c8811] dark:text-white/55"><ArrowLeft size={13}/>Back to Tata Harrier</Link>
      <div className="mt-6 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className={eyebrow}>{car.brand} {car.model} variant</p><h1 className="mt-2 text-[36px] font-semibold leading-tight text-[#0b1d17] dark:text-white sm:text-[48px]">{car.model} {car.name}</h1><p className="mt-3 text-[12px] text-[#617169] dark:text-white/58">{car.fuel} · {car.transmission}</p></div><div className="flex items-center gap-3"><span className="flex h-9 items-center gap-1.5 rounded-full border border-black/10 bg-white px-3 text-[10px] font-semibold dark:border-white/10 dark:bg-white/5"><Star size={13} fill="#86a51a" className="text-[#86a51a]"/>4.7 <span className="font-normal text-[#7c8982]">328 reviews</span></span><span className="rounded-full bg-[#e6efd4] px-3 py-2 text-[9px] font-bold text-[#58720d] dark:bg-[#c9ff49]/10 dark:text-[#c9ff49]">Best value</span></div></div>
      <div className="mt-7 grid overflow-hidden rounded-[8px] border border-black/10 bg-white shadow-[0_18px_50px_rgba(8,35,28,.10)] dark:border-white/10 dark:bg-[#0d251f] lg:grid-cols-[1.5fr_.8fr]"><div className="relative min-h-[330px] sm:min-h-[470px]"><Image src={car.image} alt={`${car.model} ${car.name} exterior`} fill priority sizes="(max-width:1024px) 100vw,65vw" className="object-cover"/><div className="absolute bottom-5 left-5 flex items-center gap-2 rounded-[7px] border border-white/40 bg-white/90 p-2 shadow-sm backdrop-blur dark:border-white/15 dark:bg-[#082019]/90">{colors.map(item=><button key={item.name} type="button" onClick={()=>setColor(item)} aria-label={`Select ${item.name}`} className={`h-6 w-6 rounded-full border-2 ${color.name===item.name?"border-[#c9ff49] ring-2 ring-black/20":"border-white"}`} style={{backgroundColor:item.value}}/>)}</div></div><div className="border-t border-black/10 p-7 dark:border-white/10 lg:border-l lg:border-t-0 lg:p-9"><p className="text-[10px] text-[#78857f] dark:text-white/45">Ex-showroom price in {city}</p><p className="mt-1 text-[26px] font-semibold text-[#10271f] dark:text-white">{car.priceLabel}</p><p className="mt-2 text-[10px] text-[#75827c] dark:text-white/45">Estimated on-road: Rs. 21.78 Lakh</p><label className="relative mt-6 block"><MapPin size={14} className="pointer-events-none absolute left-3 top-3.5 text-[#718078]"/><select value={city} onChange={e=>setCity(e.target.value)} className="h-11 w-full appearance-none rounded-[6px] border border-black/10 bg-white pl-9 pr-9 text-[11px] font-semibold outline-none dark:border-white/10 dark:bg-[#102e26] dark:text-white"><option>New Delhi</option><option>Mumbai</option><option>Jaipur</option><option>Pune</option><option>Bengaluru</option></select><ChevronDown size={14} className="pointer-events-none absolute right-3 top-3.5 text-[#718078]"/></label><button className="mt-6 h-11 w-full rounded-full bg-[#c9ff49] text-[11px] font-bold text-[#10271f]">Get exact on-road price</button><button className="mt-2 h-11 w-full rounded-full border border-[#496e61] text-[11px] font-semibold dark:border-white/25 dark:text-white">Book test drive</button></div></div>
      <div className="grid grid-cols-2 border-x border-b border-black/10 bg-white dark:border-white/10 dark:bg-[#0d251f] sm:grid-cols-5">{[["Engine",car.engine],["Power",car.power],["Torque",car.torque],["Mileage",car.mileage],["Transmission","6-speed MT"]].map(([label,value])=><div key={label} className="border-r border-t border-black/10 px-4 py-4 dark:border-white/10 sm:border-t-0"><p className="text-[9px] text-[#7b8882]">{label}</p><p className="mt-1 text-[12px] font-semibold dark:text-white">{value}</p></div>)}</div>
    </div></section>
    <nav className="sticky top-0 z-30 border-b border-black/10 bg-white/95 backdrop-blur dark:border-white/10 dark:bg-[#081b16]/95"><div className="page-shell flex h-12 items-center gap-7 overflow-x-auto [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{[["highlights","Highlights"],["price","Price"],["features","Features"],["specifications","Specifications"],["safety","Safety"],["ownership","Ownership"]].map(([id,label])=><a key={id} href={`#${id}`} className="shrink-0 text-[11px] font-semibold text-[#52665e] hover:text-[#68830e] dark:text-white/60">{label}</a>)}</div></nav>

    <Band id="highlights"><div className="page-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:gap-16"><div><Title overline="Variant overview">Why Pure Plus stands out</Title><p className="mt-4 text-[12px] leading-6 text-[#607068] dark:text-white/55">Pure Plus brings the most sought-after comfort and technology upgrades while staying well below the top variants.</p><p className="mt-6 border-l-2 border-[#91ac39] pl-4 text-[11px] leading-5 text-[#40574d] dark:text-white/65">Best for buyers who want a premium cabin without paying for ADAS or the automatic gearbox.</p></div><div className="grid border-l border-t border-black/10 dark:border-white/10 sm:grid-cols-2">{highlights.map(item=><div key={item} className="flex min-h-20 items-center gap-3 border-b border-r border-black/10 p-5 text-[11px] font-semibold text-[#30483e] dark:border-white/10 dark:text-white"><Check size={15} className="shrink-0 text-[#789611]"/>{item}</div>)}</div></div></Band>

    <Band id="price" tint><div className="page-shell grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:gap-16"><div><Title overline="Price breakdown">From showroom to your driveway</Title><dl className="mt-7 border-t border-black/10 dark:border-white/10"><PriceRow label="Ex-showroom price" value="Rs. 18.85 Lakh"/><PriceRow label="Registration estimate" value="Rs. 1.88 Lakh"/><PriceRow label="Insurance estimate" value="Rs. 0.90 Lakh"/><PriceRow label="Other charges" value="Rs. 0.15 Lakh"/><div className="flex justify-between border-b border-black/10 py-5 dark:border-white/10"><dt className="text-[11px] font-semibold dark:text-white">Estimated on-road</dt><dd className="text-[17px] font-semibold text-[#173128] dark:text-[#c9ff49]">Rs. 21.78 Lakh</dd></div></dl><p className="mt-4 text-[9px] text-[#7b8781] dark:text-white/38">Indicative figures for {city}; final charges may vary.</p></div><div className="rounded-[8px] border border-black/10 bg-white p-6 dark:border-white/10 dark:bg-[#102720] sm:p-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-[7px] bg-[#e8f1d7] text-[#68830e] dark:bg-[#c9ff49]/10 dark:text-[#c9ff49]"><IndianRupee size={18}/></span><div><p className="text-[9px] text-[#748078]">Estimated monthly EMI</p><p className="mt-1 text-[24px] font-semibold text-[#173128] dark:text-white">Rs. {new Intl.NumberFormat("en-IN").format(emi)}</p></div></div><div className="mt-7 grid gap-6"><Range label="Down payment" value={`Rs. ${down.toFixed(2)} Lakh`} min={2.5} max={10} step={0.25} current={down} update={setDown}/><Range label="Loan tenure" value={`${years} years`} min={3} max={7} step={1} current={years} update={setYears}/></div></div></div></Band>

    <Band id="features"><div className="page-shell"><Title overline="Complete equipment">Features in the Pure Plus</Title><div className="mt-9 grid border-l border-t border-black/10 dark:border-white/10 lg:grid-cols-3">{groups.map((group,index)=><div key={group.title} className="border-b border-r border-black/10 p-6 dark:border-white/10"><FeatureIcon index={index}/><h3 className="mt-5 text-[14px] font-semibold text-[#193128] dark:text-white">{group.title}</h3><div className="mt-5 grid gap-3">{group.items.map(item=><p key={item} className="flex gap-2 text-[10px] leading-5 text-[#607068] dark:text-white/55"><Check size={13} className="mt-1 shrink-0 text-[#789611]"/>{item}</p>)}</div></div>)}</div></div></Band>

    <section id="specifications" className={`${section} bg-[#08241d] text-white`}><div className="page-shell"><p className="text-[10px] font-bold uppercase text-white/50">Technical details</p><h2 className="mt-3 text-[28px] font-semibold sm:text-[34px]">Pure Plus specifications</h2><div className="mt-9 grid border-l border-t border-white/15 md:grid-cols-2">{specs.map(([label,value])=><div key={label} className="grid grid-cols-[.9fr_1.1fr] gap-4 border-b border-r border-white/15 p-4"><span className="text-[10px] text-white/45">{label}</span><span className="text-right text-[10px] font-semibold">{value}</span></div>)}</div></div></section>

    <Band id="safety" tint><div className="page-shell grid gap-12 lg:grid-cols-[1.15fr_.85fr] lg:gap-16"><div><Title overline="Safety">Strong protection is standard</Title><div className="mt-8 grid border-l border-t border-black/10 dark:border-white/10 sm:grid-cols-2">{safety.map(item=><div key={item} className="flex min-h-16 items-center gap-3 border-b border-r border-black/10 p-4 text-[10px] font-semibold text-[#40574d] dark:border-white/10 dark:text-white/65"><ShieldCheck size={14} className="shrink-0 text-[#789611]"/>{item}</div>)}</div></div><div><Title overline="Available colours">Four distinct finishes</Title><div className="mt-7 grid gap-3">{colors.map(item=><button key={item.name} onClick={()=>setColor(item)} className={`flex h-14 items-center justify-between rounded-[7px] border px-4 text-[11px] font-semibold dark:text-white ${color.name===item.name?"border-[#829f27] bg-white dark:bg-white/5":"border-black/10 dark:border-white/10"}`}><span className="flex items-center gap-3"><span className="h-7 w-7 rounded-full border border-black/10" style={{backgroundColor:item.value}}/>{item.name}</span>{color.name===item.name&&<Check size={14}/>}</button>)}</div></div></div></Band>

    <Band id="ownership"><div className="page-shell grid gap-12 lg:grid-cols-2 lg:gap-16"><div><Title overline="Ownership cover">Support after delivery</Title><div className="mt-7 border-t border-black/10 dark:border-white/10"><InfoRow icon={ShieldCheck} title="Standard warranty" value="3 years / 1 lakh km"/><InfoRow icon={Sparkles} title="Extended warranty" value="Available up to 5 years"/><InfoRow icon={Wrench} title="Service interval" value="15,000 km / 12 months"/></div></div><div><Title overline="Nearby variants">Move down or step up</Title><div className="mt-7 border-t border-black/10 dark:border-white/10">{[["Pure","Manual","Rs. 16.75 Lakh","Save Rs. 2.10 Lakh"],["Adventure Plus","Automatic","Rs. 23.64 Lakh","Add Rs. 4.79 Lakh"]].map(([name,gear,price,diff])=><article key={name} className="grid grid-cols-[1fr_auto] gap-5 border-b border-black/10 py-5 dark:border-white/10"><div><h3 className="text-[13px] font-semibold dark:text-white">Harrier {name}</h3><p className="mt-1 text-[10px] text-[#748078]">{gear} · {price}</p></div><div className="text-right"><p className="text-[9px] font-semibold text-[#66810e] dark:text-[#c9ff49]">{diff}</p><button className="mt-2 text-[10px] font-semibold dark:text-white/60">View details</button></div></article>)}</div></div></div></Band>

    <section className="bg-[#08241d] py-12 text-white"><div className="page-shell flex flex-col justify-between gap-7 lg:flex-row lg:items-center"><div><p className="text-[10px] font-bold uppercase text-white/50">Tata Harrier Pure Plus</p><h2 className="mt-3 text-[27px] font-semibold">Ready to experience it in person?</h2></div><div className="flex flex-col gap-3 sm:flex-row"><button className="inline-flex h-11 items-center justify-center gap-2 rounded-full border border-white/25 px-6 text-[11px] font-semibold"><CalendarDays size={14}/>Book test drive</button><button className="h-11 rounded-full bg-[#c9ff49] px-6 text-[11px] font-bold text-[#10271f]">Get exact price</button></div></div></section>
    <div className="fixed inset-x-0 bottom-0 z-40 border-t border-black/10 bg-white p-3 dark:border-white/10 dark:bg-[#0b211b] lg:hidden"><div className="mx-auto grid max-w-md grid-cols-2 gap-2"><button className="h-11 rounded-full border border-[#496e61] text-[10px] font-semibold dark:text-white">Test drive</button><button className="h-11 rounded-full bg-[#c9ff49] text-[10px] font-bold text-[#10271f]">Get exact price</button></div></div>
  </main>;
}

function Band({id,tint=false,children}:{id?:string;tint?:boolean;children:ReactNode}) { return <section id={id} className={`${section} ${tint?"bg-[#f3f6f3] dark:bg-[#071b16]":"bg-white dark:bg-[#0a1d18]"}`}>{children}</section>; }
function Title({overline,children}:{overline:string;children:ReactNode}) { return <div><p className={eyebrow}>{overline}</p><h2 className={heading}>{children}</h2></div>; }
function PriceRow({label,value}:{label:string;value:string}) { return <div className="flex justify-between border-b border-black/10 py-4 text-[10px] dark:border-white/10"><dt className="text-[#6c7973]">{label}</dt><dd className="font-semibold dark:text-white">{value}</dd></div>; }
function Range({label,value,min,max,step,current,update}:{label:string;value:string;min:number;max:number;step:number;current:number;update:(value:number)=>void}) { return <label className="grid gap-3 text-[10px] font-semibold dark:text-white/70"><span className="flex justify-between"><span>{label}</span><span className="text-[#68830e] dark:text-[#c9ff49]">{value}</span></span><input type="range" min={min} max={max} step={step} value={current} onChange={e=>update(Number(e.target.value))} className="accent-[#789611]"/></label>; }
function FeatureIcon({index}:{index:number}) { const icons=[Gauge,Sparkles,Palette]; const Icon=icons[index]??Settings2; return <span className="grid h-9 w-9 place-items-center rounded-[7px] bg-[#e7efd7] text-[#68830e] dark:bg-[#c9ff49]/10 dark:text-[#c9ff49]"><Icon size={16}/></span>; }
function InfoRow({icon:Icon,title,value}:{icon:typeof ShieldCheck;title:string;value:string}) { return <div className="flex items-center justify-between gap-5 border-b border-black/10 py-5 dark:border-white/10"><div className="flex items-center gap-3"><Icon size={16} className="text-[#789611]"/><span className="text-[11px] font-semibold dark:text-white">{title}</span></div><span className="text-right text-[10px] text-[#6b7872] dark:text-white/50">{value}</span></div>; }

