import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Clock3 } from "lucide-react";
import type { CarNewsStory } from "@/lib/cars/car.types";
import { getPublicUploadUrl } from "@/lib/home/home.api";

export default function ModelNewsSection({ modelName, stories }: { modelName: string; stories: CarNewsStory[] }) {
  if (stories.length === 0) return null;
  const [featured, ...rest] = stories;
  return <section id="news"><p className="text-[10px] font-semibold text-[#688078]">Updates and expert coverage</p><h2 className="mt-1 text-[26px] font-semibold sm:text-[31px]">Latest {modelName} news</h2><div className="mt-6 grid gap-3 lg:grid-cols-[1.15fr_.85fr]"><Link href={`/news/${featured.slug}`} className="group relative min-h-[330px] overflow-hidden rounded-[8px] bg-[#0a2820]">{featured.coverImageUrl && <Image src={getPublicUploadUrl(featured.coverImageUrl)!} alt="" fill sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover transition-transform duration-700 group-hover:scale-[1.03]" />}<div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(4,20,16,.02)_15%,rgba(4,20,16,.9)_100%)]" /><div className="absolute inset-x-0 bottom-0 p-5 text-white"><div className="flex items-center gap-3 text-[9px] font-semibold text-[#dfff97]"><span>{featured.category.name}</span>{featured.readTimeMinutes && <span className="flex items-center gap-1.5 text-white/60"><Clock3 size={11} />{featured.readTimeMinutes} min</span>}</div><h3 className="mt-2 text-[19px] font-semibold leading-6">{featured.title}</h3><span className="mt-4 inline-flex items-center gap-2 text-[9px] font-semibold">Read article <ArrowUpRight size={12} /></span></div></Link><div className="divide-y divide-black/[0.08] overflow-hidden rounded-[8px] border border-black/[0.08] bg-white dark:divide-white/10 dark:border-white/10 dark:bg-[#102720]">{rest.slice(0,3).map((story) => <Link key={story.id} href={`/news/${story.slug}`} className="group grid min-h-28 grid-cols-[104px_1fr] gap-3 p-3"><span className="relative overflow-hidden bg-[#e5ebe7]">{story.coverImageUrl && <Image src={getPublicUploadUrl(story.coverImageUrl)!} alt="" fill sizes="104px" className="object-cover" />}</span><span className="min-w-0 py-1"><small className="text-[8px] font-semibold text-[#688078]">{story.category.name}</small><strong className="mt-1.5 line-clamp-2 block text-[11px] leading-4">{story.title}</strong><span className="mt-3 inline-flex items-center gap-1.5 text-[8px] font-semibold text-[#315548] dark:text-[#dfff97]">Read <ArrowUpRight size={10} /></span></span></Link>)}</div></div></section>;
}
