"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BatteryCharging, CarFront } from "lucide-react";
import { useRef } from "react";
import SliderArrows from "@/components/common/SliderArrows";
import { scrollByCard } from "@/components/common/scrollByCard";
import { formatPriceRange } from "@/lib/home/home.format";
import { getPublicUploadUrl } from "@/lib/home/home.api";
import type { HomeCar } from "@/lib/home/home.types";

export default function ElectricLineupSection({ cars }: { cars: HomeCar[] }) {
  const scroller = useRef<HTMLDivElement>(null);
  if (cars.length === 0) return null;
  return <section className="bg-[#f8faf7] py-12 dark:bg-[#081b16] sm:py-14 lg:py-16"><div className="page-shell grid gap-7 lg:grid-cols-[.72fr_1.78fr] lg:items-center"><div><p className="text-[8px] font-bold uppercase tracking-[0.2em] text-[#648178]">Our electric lineup</p><h2 className="mt-2 text-[27px] font-semibold leading-tight text-[#0b1713] dark:text-white sm:text-[32px]">Find your perfect electric ride</h2><p className="mt-3 max-w-[340px] text-[10px] leading-5 text-[#6b7671] dark:text-white/60">Compare real range, battery capacity and pricing across the latest electric models.</p><div className="mt-5 flex items-center gap-3"><Link href="/electric-cars" className="inline-flex h-9 items-center gap-2 rounded-full border border-[#b9df51] px-4 text-[9px] font-bold text-[#244037] hover:bg-[#c9ff49] dark:text-white dark:hover:text-[#173027]">View all EVs <ArrowRight size={12} /></Link><SliderArrows onPrevious={() => scrollByCard(scroller.current, "left")} onNext={() => scrollByCard(scroller.current, "right")} /></div></div><div ref={scroller} className="flex snap-x snap-mandatory gap-3 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{cars.map((car) => { const image = getPublicUploadUrl(car.coverImageUrl); return <article key={car.id} className="group w-[72vw] max-w-[230px] shrink-0 snap-start overflow-hidden rounded-[6px] border border-black/[0.06] bg-white shadow-[0_7px_22px_rgba(9,31,26,.055)] dark:border-white/10 dark:bg-[#102720] sm:w-[calc((100%_-_12px)/2)] sm:max-w-none xl:w-[calc((100%_-_36px)/4)]"><div className="relative aspect-[16/10] bg-[#eef1ed]">{image ? <Image src={image} alt={`${car.brand.name} ${car.name}`} fill sizes="(max-width: 1280px) 50vw, 20vw" className="object-contain p-2 transition-transform duration-500 group-hover:scale-[1.04]" /> : <div className="grid h-full place-items-center text-[#6f817a]"><CarFront size={34} /></div>}<span className="absolute left-2.5 top-2.5 rounded-full bg-[#c9ff49] px-2 py-1 text-[7px] font-bold text-[#173027]">{car.bodyType?.name ?? "Electric"}</span></div><div className="p-3.5"><h3 className="text-[13px] font-semibold text-[#14201b] dark:text-white">{car.brand.name} {car.name}</h3><p className="mt-1.5 flex items-center gap-1.5 text-[8px] text-[#747d79] dark:text-white/55"><BatteryCharging size={11} />{car.specs?.range ? `${car.specs.range} km range` : "Range to be announced"}{car.specs?.batteryCapacity ? ` | ${car.specs.batteryCapacity} kWh` : ""}</p><div className="mt-4 flex items-center justify-between border-t border-black/[0.06] pt-3 dark:border-white/10"><p className="text-[11px] font-semibold text-[#15221c] dark:text-white">{formatPriceRange(car)}</p><Link href={`/model/${car.slug}`} aria-label={`View ${car.name}`} className="grid h-7 w-7 place-items-center rounded-full border border-[#b9dc59] text-[#27473d] hover:bg-[#c9ff49] dark:text-[#c9ff49]"><ArrowRight size={11} /></Link></div></div></article>; })}</div></div></section>;
}

