import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, CalendarDays } from "lucide-react";
import { formatLaunchDate, formatPriceRange } from "@/lib/home/home.format";
import { getPublicUploadUrl } from "@/lib/home/home.api";
import type { HomeCar } from "@/lib/home/home.types";

export default function BrandUpcomingSection({ brandName, cars }: { brandName: string; cars: HomeCar[] }) {
  if (cars.length === 0) return null;
  return <section id="upcoming" className="bg-[#edf2ef] py-10 dark:bg-[#081b16] sm:py-12"><div className="page-shell"><div className="flex items-end justify-between gap-5"><div><p className="text-[9px] font-semibold text-[#698078]">Future launches</p><h2 className="mt-1 text-[23px] font-semibold sm:text-[27px]">Upcoming {brandName} cars</h2><p className="mt-2 max-w-[560px] text-[10px] leading-5 text-[#697871] dark:text-white/48">Expected launches use protected body-type imagery until each model is officially revealed.</p></div></div><div className="mt-6 flex gap-3 overflow-x-auto pb-2 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{cars.map((car) => <Link key={car.id} href={`/model/${car.slug}`} className="group w-72 shrink-0 overflow-hidden rounded-[8px] border border-black/[0.08] bg-white dark:border-white/10 dark:bg-[#102720] sm:w-[310px]"><div style={{ aspectRatio: "16 / 9" }} className="relative overflow-hidden bg-[#dfe6e2]"><Image src={getPublicUploadUrl(car.coverImageUrl) ?? "/images/body-type-sports-car-v2.png"} alt={`Upcoming ${car.brand.name} ${car.name}`} fill sizes="310px" className="object-cover transition-transform duration-500 group-hover:scale-[1.03]" /><span className="absolute left-3 top-3 rounded-full bg-[#102f27] px-2.5 py-1 text-[9px] font-semibold text-white">Upcoming</span></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="flex items-center gap-1.5 text-[9px] text-[#697a72]"><CalendarDays size={11} />{formatLaunchDate(car.expectedLaunchDate)}</p><h3 className="mt-1.5 truncate text-[14px] font-semibold">{car.brand.name} {car.name}</h3><p className="mt-1 text-[10px] font-semibold text-[#315447] dark:text-[#dfff97]">{formatPriceRange(car)}</p></div><ArrowUpRight size={14} className="mt-1 shrink-0 text-[#597169]" /></div></div></Link>)}</div></div></section>;
}
