import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { formatPrice, formatPriceRange } from "@/lib/home/home.format";
import type { HomeCar } from "@/lib/home/home.types";

export default function BrandPriceList({ brandName, cars }: { brandName: string; cars: HomeCar[] }) {
  if (cars.length === 0) return null;
  const updatedLabel = new Intl.DateTimeFormat("en-IN", { month: "long", year: "numeric" }).format(new Date());
  return <section id="price-list" className="border-t border-black/[0.07] bg-white py-10 dark:border-white/10 dark:bg-[#0a1d18] sm:py-12"><div className="page-shell"><div className="flex items-end justify-between gap-5"><div><p className="text-[9px] font-semibold text-[#698078]">Updated {updatedLabel}</p><h2 className="mt-1 text-[23px] font-semibold sm:text-[27px]">{brandName} cars price list</h2><p className="mt-2 max-w-[560px] text-[10px] leading-5 text-[#6c7973] dark:text-white/48">Ex-showroom price ranges for every currently listed {brandName} model.</p></div><Link href="#all-models" className="hidden items-center gap-2 text-[9px] font-semibold text-[#315447] sm:flex">View model cards <ArrowUpRight size={12} /></Link></div><div className="mt-6 max-h-[540px] overflow-auto rounded-[8px] border border-black/[0.08] dark:border-white/10"><table className="w-full min-w-[620px] border-collapse text-left"><thead className="sticky top-0 z-10 bg-[#eff3f0] text-[9px] text-[#62736b] dark:bg-[#14342b] dark:text-white/55"><tr><th className="px-4 py-3 font-semibold">Model</th><th className="px-4 py-3 font-semibold">Body type</th><th className="px-4 py-3 font-semibold">Starting price</th><th className="px-4 py-3 font-semibold">Price range</th><th className="w-14 px-4 py-3" /></tr></thead><tbody className="divide-y divide-black/[0.07] bg-white dark:divide-white/10 dark:bg-[#102720]">{cars.map((car) => <tr key={car.id} className="hover:bg-[#f7f9f7] dark:hover:bg-white/[0.03]"><td className="px-4 py-3"><strong className="text-[11px] font-semibold">{car.brand.name} {car.name}</strong></td><td className="px-4 py-3 text-[10px] text-[#697871] dark:text-white/50">{car.bodyType?.name ?? "-"}</td><td className="px-4 py-3 text-[10px] font-semibold">{formatPrice(car.priceMin) ?? "To be announced"}</td><td className="px-4 py-3 text-[10px] text-[#52665d] dark:text-white/60">{formatPriceRange(car)}</td><td className="px-4 py-3"><Link href={`/model/${car.slug}`} aria-label={`View ${car.name}`} className="grid h-7 w-7 place-items-center rounded-full border border-black/10 text-[#315447] dark:border-white/15 dark:text-white"><ArrowUpRight size={11} /></Link></td></tr>)}</tbody></table></div></div></section>;
}
